# Change these first
owner: GoodVibesGaming # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Panel Frontend
    url: $PG_PANEL
    maxResponseTime: 2000
    icon: https://cdn.iconscout.com/icon/premium/png-512-thumb/website-2789449-2334235.png?f=ico&w=256
  - name: Panel API
    url: $PG_INT_API
    check: "tcp-ping"
    port: 8443
    maxResponseTime: 2000
    icon: https://cdn.iconscout.com/icon/premium/png-512-thumb/api-integration-3919190-3246461.png?f=ico&w=256
  - name: Palworld Tunnel (Connection URL)
    url: $PG_PANEL/tstat.txt
    __dangerous__body_down_if_text_missing: '"active_status": true'
    maxResponseTime: 2000
    icon: https://cdn.iconscout.com/icon/premium/png-512-thumb/tunnel-144640.png?f=ico&w=256
  - name: Palworld Server
    url: $PG_PANEL/api/client/servers/1db43d2a/resources
    headers:
      - "Authorization: Bearer $GS_API_KEY"
      - "Accept: application/json"
      - "Content-Type: application/json"
    __dangerous__body_down_if_text_missing: '"current_state":"running"'
    maxResponseTime: 2000
    icon: https://palworld.wiki.gg/favicon.ico
  - name: ATS Server
    url: $PG_PANEL/api/client/servers/fc8ff198/resources
    headers:
      - "Authorization: Bearer $GS_API_KEY"
      - "Accept: application/json"
      - "Content-Type: application/json"
    __dangerous__body_down_if_text_missing: '"current_state":"running"'
    maxResponseTime: 2000
    icon: https://trucksimulator.wiki.gg/favicon.ico
  - name: Discord Invite
    url: https://discord.gg/vxuKHHuQNk
    maxResponseTime: 3000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  robotsText: "User-agent: * \n Disallow: /"
  theme: night
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Good Vibes Gaming Status Page
  introTitle: "Got a question? Join the Discord using the link above!"
  introMessage: This status page will monitor the services needed to connect to the GoodVibes Gaming Server.
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/vxuKHHuQNk
      
i18n:
 footer: This page is [created]($REPO) ©2024 by [Good Vibes Only](https://discord.gg/vxuKHHuQNk)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
